[package]
name = "roux"
version = "1.3.8-alpha.0"
authors = ["Justin Duch <justin@duch.me>"]
edition = "2018"
license = "MIT"
description = "Simple and asyncronous Reddit API wrapper"
readme = "README.md"
documentation = "https://docs.rs/roux"
repository = "https://github.com/halcyonnouveau/roux"
keywords = ["reddit", "api", "async"]
categories = ["authentication", "api-bindings", "network-programming"]
exclude = [".circle/*", ".gitignore"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.reqwest]
version = "0.11"
features = ["json"]
optional = true

[dependencies.reqwest_backcompat]
version = "0.10"
package = "reqwest"
features = ["json"]
optional = true

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "1.1.0", features = ["rt-multi-thread", "macros"] }
tokio-test = "0.4"

[badges]
circle-ci = { repository = "halcyonnouveau/roux.rs" }

[features]
default = ["tokio_new"]
tokio_new = ["reqwest"]
tokio_back_compat = ["reqwest_backcompat"]
